name: picsaver
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pillow
  - qdrant-client
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::transformers
  - conda-forge::timm
  - einops
  - python-dotenv
  - conda-forge::rq
  - redis-py
  - loguru
  - tenacity
  - pip
  - pip:
    - asyncpg
    - "sqlalchemy[asyncio]"
    - "psycopg[binary]"
    - greenlet
    - aiogram
    - aiohttp-socks
    - aiofiles
    - requests
